import { Metadata } from 'next'

export const metadata: Metadata = {
  title: 'Building a High-Performance CDN with Cloudflare R2',
  description: 'How I architected the file storage and distribution system for Hypastack.',
  alternates: {
    canonical: '/blog/building-a-cdn',
  },
}

export default function BuildingACdn() {
  return (
    <>
      <h1 className="text-xl font-medium mb-8">Building a High-Performance CDN with Cloudflare R2</h1>

      <p className="mb-4">
        When I started building Hypastack, the biggest challenge was figuring out how to distribute large files globally without going bankrupt on egress fees. Traditional cloud providers charge exorbitant rates for outbound data transfer, which makes building a free file-sharing tool incredibly difficult.
      </p>

      <p className="mb-4">
        That's when I discovered Cloudflare R2.
      </p>

      <h2 className="text-lg font-medium mt-12 mb-4">Zero Egress Fees</h2>

      <p className="mb-4">
        Cloudflare R2 is an S3-compatible object storage service that charges exactly $0 for egress. This completely flipped the economics of my project. I could store terabytes of encrypted files and serve them millions of times without worrying about a massive AWS bill at the end of the month.
      </p>

      <h2 className="text-lg font-medium mt-12 mb-4">The Architecture</h2>

      <p className="mb-4">
        The architecture is surprisingly simple, yet incredibly fast:
      </p>

      <ul className="list-disc pl-6 mb-4 space-y-2">
        <li><strong>Uploads</strong>: Users upload files directly to an R2 bucket using pre-signed URLs generated by the Next.js backend. This means the heavy lifting is offloaded from my server entirely.</li>
        <li><strong>Encryption</strong>: Files are encrypted client-side using WebCrypto APIs before they ever touch the network.</li>
        <li><strong>Delivery</strong>: The R2 bucket is mapped to a custom domain (<code>r2.hypastack.com</code>) which sits behind Cloudflare's global CDN. When a user downloads a file, it's served directly from the edge node closest to them.</li>
      </ul>

      <h2 className="text-lg font-medium mt-12 mb-4">Cache Rules Everything Around Me</h2>

      <p className="mb-4">
        Because the files on Hypastack are immutable (they are never updated, only created and eventually deleted), I can set extremely aggressive caching headers.
      </p>

      <pre className="bg-zinc-900 p-4 rounded-xl overflow-x-auto text-sm mb-4">
        <code>{`Cache-Control: public, max-age=31536000, immutable`}</code>
      </pre>

      <p className="mb-4">
        This single header ensures that once a file is cached at an edge node, it stays there. And if a user downloads the same file twice, the second download is served instantly from their browser cache.
      </p>

      <hr className="my-8 border-zinc-800" />

      <p className="italic text-zinc-400 text-sm">
        Building a global CDN used to require a massive engineering team and a multi-million dollar budget. Today, you can do it with a few lines of configuration.
      </p>

      <script
        type="application/ld+json"
        dangerouslySetInnerHTML={{
          __html: JSON.stringify({
            "@context": "https://schema.org",
            "@type": "Article",
            "headline": "Building a High-Performance CDN with Cloudflare R2",
            "description": "How I architected the file storage and distribution system for Hypastack.",
            "author": {
              "@type": "Person",
              "name": "Kiko",
              "url": "https://usekiko.com"
            },
            "publisher": {
              "@type": "Organization",
              "name": "Kiko",
              "logo": {
                "@type": "ImageObject",
                "url": "https://r2.hypastack.com/cdn/7xcy45wytecb/kiko.png"
              }
            },
            "mainEntityOfPage": {
              "@type": "WebPage",
              "@id": "https://usekiko.com/blog/building-a-cdn"
            }
          })
        }}
      />
    </>
  )
}
